config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  resources :users, only: [:edit, :update]
  resources :listings, only: [:show, :new, :create, :edit, :update] do
    resources :reservation, only: [:show, :new, :create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/users/:id" => "users#show"
  get "/users/:id/reservations" => "users#reservations", as: "user_reservations"
  post "listings/:id/verify" => "listings#verify"
  get "/listings/:id/reservations" => "listings#reservations"
  get "/listings/find/place" => "listings#find", as: "find_listings"
  get "/listings/find/:city" => "listings#find_in", as: "find_listing_in"
  post "/find-journey" => "listings#find_journey", as: "find_journey"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  delete "/upload_listings/:id" => "upload_listings#destroy"
    post 'braintree/checkout'

    root 'application#main'

end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
    @client_token = Braintree::ClientToken.generate
  end

  def checkout
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]
    @reservation = Reservation.find(params[:braintree][:reservation_id])
    result = Braintree::Transaction.sale(
      :amount => "#{@reservation.get_total_price}",
      :payment_method_nonce => nonce_from_the_client,
      :options => {
        :submit_for_settlement => true
        }
      )
    if result.success?
      redirect_to :root, :flash => {:success => "Transaction successful!"}
      payment = Payment.new(reservation_id: @reservation.id)
      payment.amount                    = result.transaction.amount
      payment.executed_at               = result.transaction.created_at
      payment.braintree_transaction_id  = result.transaction.id
      payment.executed_at               = result.transaction.created_at
      payment.braintree_customer_id     = result.transaction.customer_details.id
      payment.save
    else
      message = "Transaction failed. Please try again."
      redirect_to :root, :flash => {:error => message}
    end
  end
    # end of class
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/views/braintree/new.html.erb
<h1>Please key in your payment details for the following Reservation</h1>
<% @reservation = get_reservation_braintree %>
<p><%= @reservation.listing.title %></p>
<p> From: <%= @reservation.from %></p>
<p>To: <%= @reservation.to %></p>
<p>______________________________</p>
<p>+ Price per night: <%= @reservation.listing.price_per_night %></p>
<p>+ Fees: <%= @reservation.listing.fees%></p>
<p>-----------------------------</p>
<p>Total: <%=get_total_price%> </p>
<p>For <%=" " + (@reservation.to - @reservation.from).to_i.to_s %> night(s) </p>
<h2>Payment:</h2>
<div class="demo-frame">
<%= form_for :checkout_form, url: braintree_checkout_path(:braintree => {:reservation_id => @reservation.id}), html: {id: "cardForm"} do |form| %>
  <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
  <div id="card-number" class="hosted-field" ></div>

  <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
  <div id="expiration-date" class="hosted-field" ></div>

  <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
  <div id="cvv" class="hosted-field" ></div>

  <%= form.hidden_field "payment_method_nonce" %>
  <div class="button-container">
    <%= form.submit "Purchase", disabled: true, class: "button button--green", id: "submit-payment-btn" %>
  </div>
  <% end %>
</div>

<script type="text/javascript">

// We generated a client token for you so you can test out this code
// immediately. In a production-ready integration, you will need to
// generate a client token on your server (see section below).
var authorization = '<%= @client_token %>';
var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");

braintree.client.create({
// Replace this with your own authorization.
authorization: '<%= @client_token %>'
}, function (clientErr, clientInstance) {
if (clientErr) {
  // Handle error in client creation
  return;
}

braintree.hostedFields.create({
  client: clientInstance,
  styles: {
    'input': {
      'font-size': '14pt'
    },
    'input.invalid': {
      'color': 'red'
    },
    'input.valid': {
      'color': 'green'
    }
  },
  fields: {
    number: {
      selector: '#card-number',
      placeholder: '4111 1111 1111 1111'
    },
    cvv: {
      selector: '#cvv',
      placeholder: '123'
    },
    expirationDate: {
      selector: '#expiration-date',
      placeholder: '10/2019'
    }
  }
}, function (hostedFieldsErr, hostedFieldsInstance) {
  if (hostedFieldsErr) {
    // Handle error in Hosted Fields creation
    return;
  }

  submit.removeAttribute('disabled');

  form.addEventListener('submit', function (event) {
    event.preventDefault();

    hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
      if (tokenizeErr) {
        // Handle error in Hosted Fields tokenization
        return;
      }

      // Put `payload.nonce` into the `payment-method-nonce` input, and then
      // submit the form. Alternatively, you could send the nonce to your server
      // with AJAX.
      document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;

      form.submit();
    });
  }, false);
});
});
</script>