config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  resources :users, only: [:edit, :update]
  resources :listings, only: [:show, :new, :create, :edit, :update] do
    resources :reservation, only: [:show, :new, :create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/users/:id" => "users#show"
  get "/users/:id/reservations" => "users#reservations", as: "user_reservations"
  post "listings/:id/verify" => "listings#verify"
  get "/listings/:id/reservations" => "listings#reservations"
  get "/listings/find/place" => "listings#find", as: "find_listings"
  get "/listings/find/:city" => "listings#find_in", as: "find_listing_in"
  post "/find-journey" => "listings#find_journey", as: "find_journey"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  delete "/upload_listings/:id" => "upload_listings#destroy"
    post 'braintree/checkout'

    root 'application#main'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  include PgSearch
  belongs_to :user
  has_many :tags, through: :listing_tags
  has_many :listing_tags, :dependent => :destroy
  has_many :upload_listings, :dependent => :destroy
  has_many :reservations, :dependent => :destroy
  scope :city, ->(city) {where("city = ?",city) if city.present?}
  scope :price_range, ->(from, to) {where("price_per_night >= ? AND price_per_night <= ?",from, to)}
  pg_search_scope :search_by_city, :against => :city
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # CRUD methods
  def new
    render '/listings/new'
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    @listing.verification = false
      # ***throws error online if price_per_night is not provided***
    if @listing.save
      redirect_to "/listings/#{@listing.id}"
    else
      render '/listings/new'
    end
  end

  def edit
    listing = Listing.find(params[:id])
    if current_user.id == listing.user_id
      render '/listings/edit'
    else
      redirect_to "/listings/#{params[:id]}"
    end
  end

  def update
    @listing = Listing.find(params[:id])
     @listing.update(listing_params)
      # this wont work with multiple true!
      # saving the image
    @listing.upload_listings.create(image: params[:listing][:image]) if  params[:listing][:image] # not nil
    if @listing.save
      redirect_to "/listings/#{@listing.id}"
    else
      render "/listings/#{@listing.id}/edit"
    end
  end

  def verify
    flash_message = "Verification was not successful! No Permission!"
    if allowed?(:verify, current_user)
      # default of verification is false
      # default of checkbox is unchecked
      # so it will always change to the oposite (if checked => true)
      @listing = Listing.find(params[:id])
      @listing.verification = not(@listing.verification)
      if @listing.save
        flash_message = "Verification was successful!"
      end
    end
    flash[:notice] = flash_message
    redirect_to "/listings/#{params[:id]}"
  end

  def reservations
    render '/listings/reservations'
  end

  def find
    render '/listings/find'
  end

  def find_in
    render '/listings/city'
  end

  def find_journey
    @listings = Listing.search_by_city(params[:destinations][:city])
    price_from = price_limits(params[:destinations][:price_from]).to_i # "".to_i => 0
    price_to = price_limits(params[:destinations][:price_to])
    price_to = 10**8 if price_to == "" || price_to == 0
    # condition ? if_true : if_false
    @listings = @listings.price_range(price_from, price_to)
    render '/destinations'
  end
################################################
    private

  def price_limits(price)
    return 0 if price == ""
    price
  end

  def listing_params
    params.require(:listing).permit(:title, :description, :country, :city,
    :zip_code, :street_address, :price_per_night, :fees)
  end

  # end of class
end

app/helpers/listings_helper.rb
module ListingsHelper
  def get_listings
    listings_array = Listing.all
  end

  def get_cities
    listing = Listing.all
    cities = []
    listing.each do |listing|
      cities << listing.city unless cities.include?(listing.city)
    end
    return cities
  end

  def get_listings_in
    listings = Listing.where(city: params[:city])
    listings
  end

  def get_listing
    listing = Listing.find(params[:id])
  end
  # for listings#show
  def get_upload_listing_urls(listing)
    uploads = listing.upload_listings
    if uploads.length > 0
      urls = []
      uploads.each do |u|
        urls << u.image.url
      end
      return urls # Array of UploadListings
    else
      return ["/uploads/upload_listing/alteriantive/alt_house.png"]
    end
  end

  # for listings#edit
  def get_uploaded_listings(listing)
    uploads = listing.upload_listings
    if uploads.length > 0
      return uploads # Array of UploadListings
    else
      return ["no image"]
    end
  end
  # end of helper
end

app/views/listings/_form.html.erb
<div class="text-field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="text-field">
  <%= form.label :description %>
  <%= form.text_field :description %>
</div>

<div class="text-field">
  <%= form.label :country %>
  <%= form.text_field :country %>
</div>

<div class="text-field">
  <%= form.label :city %>
  <%= form.text_field :city %>
</div>

<div class="text-field">
  <%= form.label :zip_code %>
  <%= form.text_field :zip_code %>
</div>

<div class="text-field">
  <%= form.label :street_address %>
  <%= form.text_field :street_address %>
</div>

<div class="text-field">
  <%= form.label :price_per_night %>
  <%= form.text_field :price_per_night %>
</div>

<div class="text-field">
  <%= form.label :fees %>
  <%= form.text_field :fees %>
</div>

app/views/listings/_show_listing.html.erb
<div>
  <strong>Description:</strong>
  <%= @listing.description %>
</div>
<div>
  <strong>Country:</strong>
  <%= @listing.country %>
</div>
<div>
  <strong>City:</strong>
  <%= @listing.city %>
</div>
<div>
  <strong>Street_address:</strong>
  <%= @listing.street_address %>
</div>
<div>
  <strong>Price per night:</strong>
  <%= @listing.price_per_night %>
</div>
<div>
  <strong>Fees:</strong>
  <%= @listing.fees %>
</div>

app/views/listings/city.html.erb
<% @listings = get_listings_in %>
<h1>Select a Place to stay in <%=params[:city] %></h1>
<% @listings.each do |listing| %>
  <%=link_to "#{listing.title}", listing_path(listing) %>
<%end %>

app/views/listings/edit.html.erb
<% @listing_id = params[:id] %>
<% @listing = Listing.find(@listing_id) %>
<h1> Please edit your Listing: <%= @listing.title %> </h1>

<%= form_for :listing, url: listing_path, method: :patch do |form| %>
  <%= render partial: "listings/form", object: form %>
  <%= form.file_field :image %>
  <p> </p>
  <%= form.submit "Save Changes" %>
  <p> </p>
<% end %>
<% get_uploaded_listings(@listing).each do |image| %>
  <% next if image == "no image" %>
  <%= image_tag  image.image.url, :class => "avatar_img" %>
  <% @image_object = image %>
  <%= form_for @image_object, url: "/#{"upload"}_listings/#{image.id}", method: :delete do |form| %>
  <%= form.submit "delete" %>
  <% end %>
<% end %>

app/views/listings/find.html.erb
<h1>Find your Place to stay here</h1>
<p> Please select a city: </p>
<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select City
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <% get_cities.each do |city| %>
      <li><a href="/listings/find/<%=city%>"><%= city %></a></li>
    <% end %>
  </ul>
</div>

app/views/listings/new.html.erb
<h1> Please fill out the form to list a new Property on CloneBnb</h1>
<%= form_for :listing, url: listings_path do |form| %>
  <%= render partial: '/listings/form', object: form %>
  <div>
      <%= form.submit %>
  </div>
<% end %>

app/views/listings/reservations.html.erb
<% @listing = get_listing2 %>
<h1>Reservations for <%=@listing.title %></h1>
<h2>-----------------------------------------------</h2>
<% @listing.reservations.each do |reservation| %>
  <p>Guest:<%= reservation.user.first_name + " " + reservation.user.last_name %></p>
  <p> From: <%= reservation.from %></p>
  <p>To: <%= reservation.to %></p>
  <p>------------------------------------</p>
<% end %>

app/views/listings/show.html.erb
<% @listing = Listing.find(params[:id]) %>
<h1> Listing: <%= @listing.title %> </h1>
<% get_upload_listing_urls(@listing).each do |url| %>
  <%= image_tag  url, :class => "avatar_img" %>
<% end %>
<%= render partial: "/listings/show_listing" %>
<% if current_user.role == "moderator" || current_user.role == "superadmin" %>
  <%= form_for :listing, url:"/listings/#{@listing.id}/verify" do |form| %>
      <%= check_box_tag(:listing, value = 1, checked = @listing.verification)  %>
      <%= form.submit "Change verification status!" %>
  <% end %>
<% end %>
<% if @listing.user_id == current_user.id %>
  <%= link_to 'Edit Listing', controller: 'listings', action: "edit" %>
  <%= link_to 'View reservations', controller: 'listings', action: "reservations" %>
<% end %>
<%= link_to "Book this palce", new_listing_reservation_path(@listing) %>
<p>This property is provided by: </p>
<a  href="/users/<%=get_listing_owner.id%>"><%= get_owner_name %></a>