config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  resources :users, only: [:edit, :update]
  resources :listings, only: [:show, :new, :create, :edit, :update] do
    resources :reservation, only: [:show, :new, :create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/users/:id" => "users#show"
  get "/users/:id/reservations" => "users#reservations", as: "user_reservations"
  post "listings/:id/verify" => "listings#verify"
  get "/listings/:id/reservations" => "listings#reservations"
  get "/listings/find/place" => "listings#find", as: "find_listings"
  get "/listings/find/:city" => "listings#find_in", as: "find_listing_in"
  post "/find-journey" => "listings#find_journey", as: "find_journey"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  delete "/upload_listings/:id" => "upload_listings#destroy"
    post 'braintree/checkout'

    root 'application#main'

end

app/models/user.rb
class User < ActiveRecord::Base
  require 'securerandom'
  require 'carrierwave/orm/activerecord'
  include Clearance::User

  has_many :authentications, :dependent => :destroy
  has_many :listings, :dependent => :destroy
  has_many :reservations, :dependent => :destroy
    # the role coloumn is integer but their value will be concerted
    # the the role: [:symbols] according to their position (0,1,2)
    # the ActiveREcord::Enum model further adds nice methods
  enum role: [:customer, :moderator, :superadmin]
    # for image uploads :avatar(=column name)
  mount_uploader :avatar, ::AvatarUploader
###########################################
  # methods
  def self.create_with_auth_and_hash(authentication, auth_hash)
     # include more user info. auth_hash needs to contain public_profile
    user = User.new(email: auth_hash["extra"]["raw_info"]["email"] )
    # more info
    user.remember_token = SecureRandom.hex(3)
    user.authentications << (authentication)
    # Problem: user.password (method from clearance) will raise error
    # although column 'encrypted_password' can be null
    # USING FACEBOOK log in. no need to save a password!
    user.password = "notgoodsolution"
    user.save
  end

  # override provide_password method here

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end
  # end of class
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
    # will redirect a not login user when triying
    # to access actions within the UserController
   before_action :require_login
      # Logical, because other wise noone could
      # send a post request for creating an account
   skip_before_action :require_login, only: [:create, :new], raise: false

  def show
    render '/users/show'
  end
    # controller for post "/users" request
  def create
    @user = User.new(user_params)
    @user.role = 0
      # roles:
      # 0 = customer; 1 = moderator; 2 = superadmin

      # actions can respond differently
      # to various request formats being sent
    respond_to do |format|
      if @user.save
        format.html {
          sleep 1
          render template: "users/new"
        }
        format.js {
          sign_in @user
          redirect_back_or url_after_create
        }

      else
        format.html {render template: "users/new"}
        format.js {} # automatically render create.js.erb (rails magic)
      end
    end
    # end of create
  end

  def edit
    render '/users/edit'
  end
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    @user.avatar = params[:user][:avatar]
    if @user.save
      flash[:notice] = "Changes successfully saved!"
    else
      flash[:notice] = "Changes could not be saved!"
    end
    render '/users/show'
  end

  def reservations
    render '/users/reservations'
  end
private
  # Overriding method from Clearance gem in order to
  # create user with more attrbutes
  # than just email and password
  def user_params
    params.require(:user).permit(:first_name, :last_name, :gender,
     :email, :password, :avatar)
  end

  def change_attributes!(attr, strong_params, user)
    attribute = attr[0].to_sym
    user[attribute] = strong_params[attribute]  unless strong_params[attribute] == ""
  end
  #  end of controller
end

app/helpers/users_helper.rb
module UsersHelper
  # get user_name in Listing
  def get_owner_name
        # params are automatically passed to the function
    owner =  User.find(Listing.find(params["id"]).user_id)
    if owner.first_name && owner.last_name
      name = owner.first_name + " " + owner.last_name
    elsif owner.first_name
      name = owner.first_name
    elsif owner.last_name
      name = owner.last_name
    else
      return owner.email
    end
    return name
  end

  def get_listing_owner
    @user = User.find(Listing.find(params[:id]).user_id)
  end

  # end of module
end

app/views/users/_edit_form.html.erb
<div class="text-field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>
</div>

<div class="text-field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name %>
</div>

<div class="text-field">
  <%= form.label :gender %>
  <%= form.text_field :gender %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>
</div>

<div class="text-field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name %>
</div>

<div class="text-field">
  <%= form.label :gender %>
  <%= form.text_field :gender %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/_show_user.html.erb
<div>
  <strong>First name:</strong>
  <%= @user.first_name %>
</div

<div>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</div>
<div>
  <strong>Gender:</strong>
  <%= @user.gender %>
</div>
<div>
  <strong>Email:</strong>
  <%= @user.email %>
</div>

app/views/users/create.js.erb
//  this file will be rendered when the user types
// in invalid data in the sign up form
// Controller: UserController
// Action: #create
alert("Wrong input! Please check your inserted data.")

app/views/users/edit.html.erb
<h1> Hey <%= current_user.first_name%> </h1>
<h2> Please edit your Profile here: </h2>
<%= form_for current_user do |form| %>
  <%= render partial: '/users/edit_form', locals: {form: form} %>
  <div class="submit-field">
    <div>
      <%= form.file_field :avatar %>
    </div>
    <%= form.submit "Save changes!" %>
  </div>
<% end %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>
  <!-- remote: true will send the request
  as a js request; not as a post html request anymore -->
  <%= form_for @user, url: "/users", remote: true do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/reservations.html.erb
<% @user = current_user %>
<h1>Hello <%=@user.first_name %></h1>
<h2>Here are your reservations:</h2>
<% @user.reservations.each do |reservation| %>
  <p><%= reservation.listing.title %></p>
  <p> From: <%= reservation.from %></p>
  <p>To: <%= reservation.to %></p>
  <%if not(payed?(reservation)) %>
    <%= link_to "Make payment", braintree_new_path(:braintree => {:reservation_id => reservation.id}) %>
  <% else %>
    <p>PAID</p>
  <%end %>
  <p>------------------------------------</p>
<% end %>

app/views/users/show.html.erb
<% @user = User.find(params[:id]) %>
<h1>Hello <%=@user.first_name %></h1>
<%= image_tag @user.avatar.url, :class => "avatar_img" %>
<%= render partial: "/users/show_user" %>
<% if current_user.id.to_s == params[:id] %>
  <%= link_to "Edit Profile", edit_user_path %>
  <%= link_to "My Reservations", user_reservations_path%>
<% end %>