config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  resources :users, only: [:edit, :update]
  resources :listings, only: [:show, :new, :create, :edit, :update] do
    resources :reservation, only: [:show, :new, :create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/users/:id" => "users#show"
  get "/users/:id/reservations" => "users#reservations", as: "user_reservations"
  post "listings/:id/verify" => "listings#verify"
  get "/listings/:id/reservations" => "listings#reservations"
  get "/listings/find/place" => "listings#find", as: "find_listings"
  get "/listings/find/:city" => "listings#find_in", as: "find_listing_in"
  post "/find-journey" => "listings#find_journey", as: "find_journey"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  delete "/upload_listings/:id" => "upload_listings#destroy"
    post 'braintree/checkout'

    root 'application#main'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clonebnb</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <!-- Load the Client component.braintree -->
  <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>
  <!-- Load the Hosted Fields component.braintree -->
  <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header">
    <%= link_to "Home", "/"%>
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
      <%= link_to "My Profile", "/users/#{current_user.id}" %>
      <%= link_to "Create Listing", controller: 'listings', action: 'new' %> <br></br>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %> <br> </br>
      <%= link_to "Sign in with Facebook", "/auth/facebook" %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div class="<%= flash_class(key) %>" id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>